/**
 * SEO utilities for B LEADER
 * Next.js App Router — metadata, JSON-LD schemas, canonical helpers.
 *
 * Target audience: US luxury travelers discovering Salento / Puglia experiences.
 */

/** Official production domains (Cloudflare Workers custom domains). */
export const OFFICIAL_DOMAINS = {
  primary: "bleaderitaly.com",
  italy: "bleaderitaly.it",
} as const;

export const SITE = {
  name: "B LEADER",
  tagline: "Luxury Driving & Yacht Experiences in Salento",
  // Primary public URL — override with NEXT_PUBLIC_SITE_URL in prod if needed
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://bleaderitaly.com",
  domains: OFFICIAL_DOMAINS,
  locale: "en_US",
  htmlLang: "en-US",
  localeAlternate: "it_IT",
  defaultTitle:
    "B LEADER — Luxury Driving & Yacht Experiences in Salento, Italy",
  defaultDescription:
    "Live the Italian dream: drive a Ferrari along the Adriatic coast or sail into a Puglian sunset on a private yacht. Curated luxury experiences in Salento for international travelers — English-speaking concierge, professional photographer, champagne included.",
  defaultKeywords: [
    // Core brand + product
    "B LEADER luxury experiences",
    "Ferrari driving experience Salento Italy",
    "Ferrari rental Puglia",
    "luxury yacht charter Salento",
    "luxury car rental Salento Italy",
    // US traveler intent
    "luxury vacation Puglia for Americans",
    "drive Ferrari Italy vacation",
    "exotic car experience Italy from USA",
    "Salento luxury travel for US tourists",
    "honeymoon yacht charter Puglia",
    "supercar tour Southern Italy",
    // Destination modifiers
    "Puglia supercar experience",
    "sunset yacht tour Adriatic",
    "Ferrari California tour Italy",
    "Lecce Gallipoli Otranto luxury tours",
  ],
  /** Default OG image — generated by app/opengraph-image.tsx */
  ogImage: "/opengraph-image",
  twitterHandle: process.env.NEXT_PUBLIC_TWITTER_HANDLE || undefined,
} as const;

/**
 * Contact from env (fallbacks are public-safe defaults only).
 * Set real phone in wrangler vars / .env — never commit secrets.
 */
export const CONTACT = {
  phone: process.env.NEXT_PUBLIC_PHONE || "",
  email: process.env.NEXT_PUBLIC_EMAIL || "info@bleaderitaly.com",
  /** Optional street address for LocalBusiness richness */
  streetAddress: process.env.NEXT_PUBLIC_STREET_ADDRESS || undefined,
  addressLocality: process.env.NEXT_PUBLIC_ADDRESS_LOCALITY || "Lecce",
  addressRegion: process.env.NEXT_PUBLIC_ADDRESS_REGION || "Puglia",
  postalCode: process.env.NEXT_PUBLIC_POSTAL_CODE || undefined,
  addressCountry: "IT",
  /** WGS84 — set when base of operations is confirmed */
  geo:
    process.env.NEXT_PUBLIC_GEO_LAT && process.env.NEXT_PUBLIC_GEO_LNG
      ? {
          lat: process.env.NEXT_PUBLIC_GEO_LAT,
          lng: process.env.NEXT_PUBLIC_GEO_LNG,
        }
      : undefined,
};

/**
 * Brand social profiles for JSON-LD sameAs.
 * Prefer comma-separated NEXT_PUBLIC_SAME_AS, or individual NEXT_PUBLIC_SOCIAL_* vars.
 * Empty entries are filtered — never emit placeholder URLs.
 */
export function getSameAs(): string[] {
  const fromList =
    process.env.NEXT_PUBLIC_SAME_AS?.split(",")
      .map((s) => s.trim())
      .filter((s) => s.startsWith("http")) ?? [];

  const individuals = [
    process.env.NEXT_PUBLIC_SOCIAL_INSTAGRAM,
    process.env.NEXT_PUBLIC_SOCIAL_FACEBOOK,
    process.env.NEXT_PUBLIC_SOCIAL_X,
    process.env.NEXT_PUBLIC_SOCIAL_LINKEDIN,
    process.env.NEXT_PUBLIC_SOCIAL_YOUTUBE,
    process.env.NEXT_PUBLIC_SOCIAL_TRIPADVISOR,
  ]
    .map((s) => s?.trim())
    .filter((s): s is string => !!s && s.startsWith("http"));

  return Array.from(new Set([...fromList, ...individuals]));
}

export type PageMeta = {
  title: string;
  description: string;
  path: string;
  keywords?: string[];
  ogImage?: string;
  noIndex?: boolean;
};

/**
 * Consistent page metadata for App Router.
 * Title suffix "| B LEADER" is applied for non-home paths.
 */
export function buildPageMeta(page: PageMeta) {
  const title =
    page.path === "/" ? page.title : `${page.title} | ${SITE.name}`;
  const description = page.description || SITE.defaultDescription;
  const canonicalPath = page.path === "/" ? "/" : page.path;
  const absoluteUrl = `${SITE.url}${canonicalPath === "/" ? "" : canonicalPath}`;
  const images = page.ogImage
    ? [{ url: page.ogImage, width: 1200, height: 630, alt: title }]
    : [{ url: SITE.ogImage, width: 1200, height: 630, alt: title }];

  return {
    title,
    description,
    keywords: [...SITE.defaultKeywords, ...(page.keywords ?? [])],
    metadataBase: new URL(SITE.url),
    alternates: {
      canonical: canonicalPath,
      languages: {
        "en-US": canonicalPath,
        "x-default": canonicalPath,
      },
    },
    openGraph: {
      title,
      description,
      url: absoluteUrl,
      siteName: SITE.name,
      type: "website" as const,
      locale: SITE.locale,
      images,
    },
    twitter: {
      card: "summary_large_image" as const,
      title,
      description,
      images: images.map((i) => i.url),
      ...(SITE.twitterHandle
        ? { creator: SITE.twitterHandle, site: SITE.twitterHandle }
        : {}),
    },
    robots: page.noIndex
      ? { index: false, follow: false }
      : {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            "max-video-preview": -1,
            "max-image-preview": "large" as const,
            "max-snippet": -1,
          },
        },
  };
}

// ──────────────────────────────────────────────
// JSON-LD Schema helpers
// ──────────────────────────────────────────────

/**
 * Organization + LocalBusiness schema.
 * Signals English service, EUR/USD, Salento service area for international visitors.
 */
export function localBusinessSchema() {
  const sameAs = getSameAs();
  const telephone = CONTACT.phone || undefined;

  return {
    "@context": "https://schema.org",
    "@type": ["Organization", "LocalBusiness", "TouristInformationCenter"],
    "@id": `${SITE.url}/#organization`,
    name: SITE.name,
    legalName: SITE.name,
    url: SITE.url,
    logo: {
      "@type": "ImageObject",
      url: `${SITE.url}/images/logo-white.webp`,
    },
    image: [`${SITE.url}/images/hero-bg.webp`, `${SITE.url}/opengraph-image`],
    description: SITE.defaultDescription,
    slogan: SITE.tagline,
    priceRange: "$$$$",
    currenciesAccepted: "EUR, USD",
    paymentAccepted: "Credit Card, Bank Transfer",
    availableLanguage: ["English", "Italian"],
    knowsLanguage: ["en", "it"],
    ...(telephone ? { telephone } : {}),
    email: CONTACT.email,
    address: {
      "@type": "PostalAddress",
      ...(CONTACT.streetAddress
        ? { streetAddress: CONTACT.streetAddress }
        : {}),
      addressLocality: CONTACT.addressLocality,
      addressRegion: CONTACT.addressRegion,
      ...(CONTACT.postalCode ? { postalCode: CONTACT.postalCode } : {}),
      addressCountry: CONTACT.addressCountry,
    },
    ...(CONTACT.geo
      ? {
          geo: {
            "@type": "GeoCoordinates",
            latitude: CONTACT.geo.lat,
            longitude: CONTACT.geo.lng,
          },
        }
      : {}),
    areaServed: [
      { "@type": "AdministrativeArea", name: "Salento" },
      { "@type": "AdministrativeArea", name: "Puglia" },
      { "@type": "City", name: "Lecce" },
      { "@type": "City", name: "Gallipoli" },
      { "@type": "City", name: "Otranto" },
      { "@type": "City", name: "Brindisi" },
      { "@type": "City", name: "Bari" },
      { "@type": "City", name: "Santa Maria di Leuca" },
    ],
    openingHoursSpecification: [
      {
        "@type": "OpeningHoursSpecification",
        dayOfWeek: [
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday",
          "Friday",
        ],
        opens: "09:00",
        closes: "19:00",
      },
      {
        "@type": "OpeningHoursSpecification",
        dayOfWeek: "Saturday",
        opens: "10:00",
        closes: "16:00",
      },
    ],
    ...(sameAs.length > 0 ? { sameAs } : {}),
    hasOfferCatalog: {
      "@type": "OfferCatalog",
      name: "B LEADER Luxury Experiences",
      itemListElement: [
        {
          "@type": "OfferCatalog",
          name: "Supercar & Luxury Car Experiences",
          itemListElement: [
            {
              "@type": "Offer",
              itemOffered: {
                "@type": "Service",
                name: "Ferrari Driving Experience — Salento",
                description:
                  "Self-drive Ferrari experiences along the Adriatic and Ionian coasts of Salento, with English-speaking concierge.",
                provider: { "@id": `${SITE.url}/#organization` },
                areaServed: "Salento, Puglia, Italy",
                url: `${SITE.url}/fleet`,
              },
            },
            {
              "@type": "Offer",
              itemOffered: {
                "@type": "Service",
                name: "Luxury Car Rental — Maserati & Mercedes",
                description:
                  "Premium self-drive rentals for coastal touring and special occasions in Southern Italy.",
                provider: { "@id": `${SITE.url}/#organization` },
                url: `${SITE.url}/fleet`,
              },
            },
          ],
        },
        {
          "@type": "OfferCatalog",
          name: "Yacht Charters",
          itemListElement: [
            {
              "@type": "Offer",
              itemOffered: {
                "@type": "Service",
                name: "Private Yacht Charter — Salento Coast",
                description:
                  "Private yacht experiences on the Adriatic and Ionian seas — sunset sails, couples, and celebrations.",
                provider: { "@id": `${SITE.url}/#organization` },
                areaServed: "Salento, Adriatic Sea, Ionian Sea",
                url: `${SITE.url}/yacht`,
              },
            },
          ],
        },
        {
          "@type": "OfferCatalog",
          name: "Curated Experiences",
          itemListElement: [
            {
              "@type": "Offer",
              itemOffered: {
                "@type": "TouristTrip",
                name: "B LEADER Concierge Experiences",
                description:
                  "Weddings, proposals, corporate days, and photographer-included luxury itineraries in Salento.",
                touristType: "Luxury travelers, couples, US & international guests",
                url: `${SITE.url}/services`,
              },
            },
          ],
        },
      ],
    },
  };
}

/** WebSite schema — helps sitelinks / brand search understanding */
export function websiteSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": `${SITE.url}/#website`,
    name: SITE.name,
    url: SITE.url,
    description: SITE.defaultDescription,
    inLanguage: "en-US",
    publisher: { "@id": `${SITE.url}/#organization` },
  };
}

export type Vehicle = {
  name: string;
  image: string;
  pricePerDay?: number;
  currency?: string;
  description: string;
  brand: string;
  category: "Car" | "Yacht";
};

/**
 * Product schema for rental vehicles.
 * UnitPriceSpecification = daily rental (not sale).
 */
export function productSchema(vehicle: Vehicle) {
  return {
    "@context": "https://schema.org",
    "@type": "Product",
    name: vehicle.name,
    brand: { "@type": "Brand", name: vehicle.brand },
    category: `${vehicle.category} Rental`,
    image: vehicle.image,
    description: vehicle.description,
    offers: {
      "@type": "Offer",
      priceCurrency: vehicle.currency ?? "EUR",
      price: vehicle.pricePerDay ?? undefined,
      priceSpecification: vehicle.pricePerDay
        ? {
            "@type": "UnitPriceSpecification",
            unitText: "DAY",
            price: vehicle.pricePerDay,
            priceCurrency: vehicle.currency ?? "EUR",
          }
        : undefined,
      availability: "https://schema.org/InStock",
      url: vehicle.category === "Yacht" ? `${SITE.url}/yacht` : `${SITE.url}/fleet`,
      seller: { "@id": `${SITE.url}/#organization` },
    },
  };
}

/** BreadcrumbList — site hierarchy for SERP */
export function breadcrumbSchema(items: { name: string; path: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      item: `${SITE.url}${item.path === "/" ? "" : item.path}`,
    })),
  };
}

/** FAQPage schema — rich results for US-intent landing FAQs */
export function faqSchema(faqs: { question: string; answer: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((faq) => ({
      "@type": "Question",
      name: faq.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: faq.answer,
      },
    })),
  };
}

/** TouristTrip / Service schema for experience landing pages */
export function experienceSchema(opts: {
  name: string;
  description: string;
  path: string;
  image?: string;
}) {
  return {
    "@context": "https://schema.org",
    "@type": "TouristTrip",
    name: opts.name,
    description: opts.description,
    url: `${SITE.url}${opts.path}`,
    image: opts.image ? `${SITE.url}${opts.image}` : `${SITE.url}/opengraph-image`,
    touristType: "Luxury travelers, couples, US and international guests",
    itinerary: {
      "@type": "Place",
      name: "Salento, Puglia, Italy",
      address: {
        "@type": "PostalAddress",
        addressRegion: "Puglia",
        addressCountry: "IT",
      },
    },
    provider: { "@id": `${SITE.url}/#organization` },
  };
}
